In [2]:
import pandas as pd
data0 = pd.read_csv('gesture0_new.csv')
data1 = pd.read_csv('gesture1_new.csv')
data2 = pd.read_csv('gesture2_new.csv')
data3 = pd.read_csv('gesture3_new.csv')
data4 = pd.read_csv('gesture4_new.csv')
data5 = pd.read_csv('gesture5_new.csv')
data6 = pd.read_csv('gesture6_new.csv')
data7 = pd.read_csv('gesture7_new.csv')
data8 = pd.read_csv('gesture8_new.csv')
data9 = pd.read_csv('gesture9_new.csv')
 
# df.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)
# n = number of rows(optional, cannot be used with frac) 抽取的行数；
# frac = fraction/proportion(optional, cannot be used with n) 抽取的比例；
# replace = Allow or disallow sampling of the same row more than once (boolean, default False) 是否为有放回抽样；
# weights (str or ndarray-like, optional) 权重
# random_state (int to use as interval, or call np.random.get_state(), optional) 整数作为间隔，或者调用np.random.get_state()
# axis = extract row or column (0->row, 1->column) 抽取行还是列（0是行，1是列）
 
# random select 10% from dataset
sample0 = data0.sample(frac=0.2)
sample1 = data1.sample(frac=0.1)
sample2 = data2.sample(frac=0.1)
sample3 = data3.sample(frac=0.1)
sample4 = data4.sample(frac=0.1)
sample5 = data5.sample(frac=0.1)
sample6 = data6.sample(frac=0.1)
sample7 = data7.sample(frac=0.1)
sample8 = data8.sample(frac=0.1)
sample9 = data9.sample(frac=0.1)

# export to csv file
sample0.to_csv('fingerdata0_postnew.csv',index=False)
sample1.to_csv('fingerdata1_postnew.csv',index=False)
sample2.to_csv('fingerdata2_postnew.csv',index=False)
sample3.to_csv('fingerdata3_postnew.csv',index=False)
sample4.to_csv('fingerdata4_postnew.csv',index=False)
sample5.to_csv('fingerdata5_postnew.csv',index=False)
sample6.to_csv('fingerdata6_postnew.csv',index=False)
sample7.to_csv('fingerdata7_postnew.csv',index=False)
sample8.to_csv('fingerdata8_postnew.csv',index=False)
sample9.to_csv('fingerdata9_postnew.csv',index=False)

# df = pd.read_csv('fingerdata1_post.csv')
# df = df.drop(sample.columns[[0]],axis=1)
# df.to_csv('fingerdata1_post1.csv')

In [15]:
finger0 = pd.read_csv('fingerdata0_post.csv')
finger1 = pd.read_csv('fingerdata1_post.csv')
finger2 = pd.read_csv('fingerdata2_post.csv')
finger3 = pd.read_csv('fingerdata3_post.csv')
finger4 = pd.read_csv('fingerdata4_post.csv')
finger5 = pd.read_csv('fingerdata5_post.csv')
finger6 = pd.read_csv('fingerdata6_post.csv')
finger7 = pd.read_csv('fingerdata7_post.csv')
finger8 = pd.read_csv('fingerdata8_post.csv')
finger9 = pd.read_csv('fingerdata9_post.csv')
#df = finger0.append(finger1,ignore_index=True).append(finger2,ignore_index=True).append(finger3,ignore_index=True).append(finger4,ignore_index=True).append(finger5,ignore_index=True).append(finger6,ignore_index=True).append(finger7,ignore_index=True).append(finger8,ignore_index=True).append(finger9,ignore_index=True)
df = pd.concat([finger0,finger1,finger2,finger3,finger4,finger5,finger6,finger7,finger8,finger9],ignore_index=True)
df = df.astype(int)
df.to_csv('fingerdata_forknn1.csv',index=False,)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [12]:
import numpy as np

data = np.empty([1,6])
x_train = np.load('train_test/x_train.npy')*1023
x_test = np.load('train_test/x_test.npy')
y_train = np.load('train_test/y_train.npy')
y_test = np.load('train_test/y_test.npy')

x_train = np.round(x_train)
x_train.astype(int)
y_train = np.reshape(y_train, (-1, 1))
train = np.hstack((x_train, y_train))
np.around(train, decimals=1)

for i in range(10):
    mask = train[:, -1] == i
    train[mask, :]
    data = np.concatenate((data, train[np.random.choice(train.shape[0], 110, replace=False), :]))
    
data = data[data[:,5].argsort()]
np.savetxt("knndata.csv", data ,fmt='%i',  delimiter=",")

In [32]:
train.shape

(14000, 6)

In [12]:
print(x_train)
x_train.shape

[[0.63049853 0.66764418 0.69403715 0.53958944 0.30107527]
 [0.52688172 0.52101662 0.51026393 0.67741935 0.30694037]
 [0.65102639 0.57184751 0.57086999 0.55620723 0.38807429]
 ...
 [0.68426197 0.70576735 0.71065494 0.70772239 0.25904203]
 [0.41837732 0.48680352 0.46920821 0.40273705 0.27077224]
 [0.53274682 0.52394917 0.69990225 0.68523949 0.31378299]]


(14000, 5)

In [11]:
print(y_train)
print(y_train.shape)

[3 1 6 ... 4 0 2]
(14000,)


In [26]:
y_train = np.reshape(y_train, (-1, 1))

In [27]:
np.transpose(y_train).shape

(1, 14000)

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

#url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"   # Assign colum names to the dataset
#names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']    # Read dataset to pandas dataframe
#dataset = pd.read_csv(url, names=names)

names = ['thumb', 'index', 'middle', 'ring', 'little', 'gesture']
dataset = pd.read_csv('fingerdata_forknn1.csv', names=names)
dataset_test = pd.read_csv('fingerdata.csv', names=names)
dataset_test = dataset_test.sample(frac=0.1)

X_train = dataset.iloc[:, :-1].values
y_train = dataset.iloc[:, 5].values

X_test = dataset_test.iloc[:, :-1].values
y_test = dataset_test.iloc[:, 5].values
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)    #20% for test



classifier = KNeighborsClassifier(n_neighbors=10)   #hyperparameter of KNN --- k
classifier.fit(X_train, y_train)       #training
y_pred = classifier.predict(X_test)   #prediction


#evaluation of the algorithm
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


error = []
# Calculating error for K values between 1 and 40
for i in range(1, 40):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))

fig = plt.figure(figsize=(12, 6))
plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')
plt.show()
fig.savefig('test_error9.png', dpi=fig.dpi)
print(error)

ModuleNotFoundError: No module named 'sklearn'

In [2]:
data0

thumb  index  middle  ring  little  gesture
0       373    446     441   515     489        0
1       373    446     442   516     489        0
2       373    446     442   515     489        0
3       372    446     441   514     488        0
4       372    446     442   514     489        0
...     ...    ...     ...   ...     ...      ...
1439    356    485     475   514     485        0
1440    355    485     475   514     485        0
1441    356    485     473   514     486        0
1442    355    485     474   515     485        0
1443    355    485     474   513     485        0

[1444 rows x 6 columns]

In [5]:
#df = finger0.append(finger1,ignore_index=True).append(finger2,ignore_index=True).append(finger3,ignore_index=True).append(finger4,ignore_index=True).append(finger5,ignore_index=True).append(finger6,ignore_index=True).append(finger7,ignore_index=True).append(finger8,ignore_index=True).append(finger9,ignore_index=True)
data0 = data0[['little','ring','middle','index','thumb','gesture']]
data1 = data1[['little','ring','middle','index','thumb','gesture']]
data2 = data2[['little','ring','middle','index','thumb','gesture']]
data3 = data3[['little','ring','middle','index','thumb','gesture']]
data4 = data4[['little','ring','middle','index','thumb','gesture']]
data5 = data5[['little','ring','middle','index','thumb','gesture']]
data6 = data6[['little','ring','middle','index','thumb','gesture']]
data7 = data7[['little','ring','middle','index','thumb','gesture']]
data8 = data8[['little','ring','middle','index','thumb','gesture']]
data9 = data9[['little','ring','middle','index','thumb','gesture']]


data0['thumb'] -= 70
data0['index'] += 100
data0['middle'] += 100
data0['ring'] += 50
data0['little'] += 30

data1['thumb'] -= 70
data1['index'] += 100
data1['middle'] += 100
data1['ring'] += 50
data1['little'] += 30

data2['thumb'] -= 70
data2['index'] += 100
data2['middle'] += 100
data2['ring'] += 50
data2['little'] += 30

data3['thumb'] -= 70
data3['index'] += 100
data3['middle'] += 100
data3['ring'] += 50
data3['little'] += 30

data4['thumb'] -= 70
data4['index'] += 100
data4['middle'] += 100
data4['ring'] += 50
data4['little'] += 30

data5['thumb'] -= 70
data5['index'] += 100
data5['middle'] += 100
data5['ring'] += 50
data5['little'] += 30

data6['thumb'] -= 70
data6['index'] += 100
data6['middle'] += 100
data6['ring'] += 50
data6['little'] += 30

data7['thumb'] -= 70
data7['index'] += 100
data7['middle'] += 100
data7['ring'] += 50
data7['little'] += 30

data8['thumb'] -= 70
data8['index'] += 100
data8['middle'] += 100
data8['ring'] += 50
data8['little'] += 30

data9['thumb'] -= 70
data9['index'] += 100
data9['middle'] += 100
data9['ring'] += 50
data9['little'] += 30

data0.to_csv('fingerdata-zjt/fingerdata0.csv',index=False,)
data1.to_csv('fingerdata-zjt/fingerdata1.csv',index=False,)
data2.to_csv('fingerdata-zjt/fingerdata2.csv',index=False,)
data3.to_csv('fingerdata-zjt/fingerdata3.csv',index=False,)
data4.to_csv('fingerdata-zjt/fingerdata4.csv',index=False,)
data5.to_csv('fingerdata-zjt/fingerdata5.csv',index=False,)
data6.to_csv('fingerdata-zjt/fingerdata6.csv',index=False,)
data7.to_csv('fingerdata-zjt/fingerdata7.csv',index=False,)
data8.to_csv('fingerdata-zjt/fingerdata8.csv',index=False,)
data9.to_csv('fingerdata-zjt/fingerdata9.csv',index=False,)

In [6]:
data0

little  ring  middle  index  thumb  gesture
0        549   615     641    646    233        0
1        549   616     642    646    233        0
2        549   615     642    646    233        0
3        548   614     641    646    232        0
4        549   614     642    646    232        0
...      ...   ...     ...    ...    ...      ...
1439     545   614     675    685    216        0
1440     545   614     675    685    215        0
1441     546   614     673    685    216        0
1442     545   615     674    685    215        0
1443     545   613     674    685    215        0

[1444 rows x 6 columns]